### ISSUE TITLE
https??

### ISSUE THREAD

**Issue by baha00** [rdegges/okta-express-login-portal#4]
is it possible to implement https in bin/www script??

**Comment by rdegges** [comment]
Yes, you can implement that however you'd like.

**Comment by baha00** [comment]
how?
adding this line is crashing it
var secureserver = https.createServer(app);

**Comment by rdegges** [comment]
You can't just use `https` because there is no variable `https` defined. You also haven't defined a cert or anything. I can't explain it in just one comment, but typically you would have a server (like NGINX, for example) terminate SSL for your app.

If you'd actually like Node to terminal SSL (not recommended), this article explains how: https://nodejs.org/en/knowledge/HTTP/servers/how-to-create-a-HTTPS-server/

This isn't something I'd typically put into a project like this because that is handled at a different layer (the infrastructure layer), not typically in the application code...
